# Generated by Django 5.1.5 on 2025-02-02 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articulos',
            fields=[
                ('idarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('codigoarticulo', models.CharField(max_length=10, unique=True, verbose_name='Código de Producto ')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen')),
                ('nombre_articulo', models.CharField(max_length=100, verbose_name='Nombre ')),
                ('descripcion_articulo', models.CharField(max_length=255, verbose_name='Descripción ')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Base')),
                ('estado_articulo', models.IntegerField(default=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulos',
            },
        ),
        migrations.CreateModel(
            name='Categoriaarticulos',
            fields=[
                ('idcategoriaarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_categoriaarticulo', models.CharField(max_length=100, verbose_name='Descripción ')),
            ],
            options={
                'verbose_name': 'Categoría Artículo',
                'verbose_name_plural': 'Categoría Artículos',
                'db_table': 'categoriaarticulos',
            },
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('CarritoID', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_productos', models.IntegerField(default=0)),
                ('productos', models.ManyToManyField(to='ventas.articulos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idcliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=30, verbose_name='Nombre ')),
                ('correo_cliente', models.EmailField(max_length=80, verbose_name='Correo ')),
                ('celular_cliente', models.CharField(max_length=10, verbose_name='Celular ')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección ')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='SubcategoriaArticulos',
            fields=[
                ('idsubcategoriaarticulo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_subcategoriaarticulo', models.CharField(max_length=100, verbose_name='Descripción ')),
                ('idcategoriaarticulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.categoriaarticulos')),
            ],
            options={
                'verbose_name': 'Subcategoría Artículo',
                'verbose_name_plural': 'Subcategoría Artículos',
                'db_table': 'subcategoriaarticulos',
            },
        ),
        migrations.AddField(
            model_name='articulos',
            name='idsubcategoriaarticulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='ventas.subcategoriaarticulos', verbose_name='Subcategoría'),
        ),
        migrations.CreateModel(
            name='VarianteArticulo',
            fields=[
                ('idvariante', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_variante', models.CharField(choices=[('ropa', 'Talla de ropa'), ('calzado', 'Número de calzado')], max_length=10, verbose_name='Tipo de Variante')),
                ('talla_ropa', models.CharField(blank=True, max_length=5, null=True, verbose_name='Talla de Ropa')),
                ('numero_calzado', models.IntegerField(blank=True, null=True, verbose_name='Número de Calzado')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('precio_adicional', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Precio Adicional')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='ventas.articulos', verbose_name='Artículo')),
            ],
            options={
                'verbose_name': 'Variante de Artículo',
                'verbose_name_plural': 'Variantes de Artículos',
                'db_table': 'variantes_articulo',
            },
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('ItemCarritoID', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.carrito')),
                ('variante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.variantearticulo')),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('idventa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('idcliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Detalle_ventas',
            fields=[
                ('iddetalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Precio Unitario')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('idventa', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ventas.ventas', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle Venta',
                'verbose_name_plural': 'Detalle Ventas',
                'db_table': 'detalle_ventas',
            },
        ),
    ]
