# Generated by Django 5.1.5 on 2025-02-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total')),
                ('numero_autorizacion', models.CharField(max_length=50, unique=True, verbose_name='Número de Autorización')),
                ('clave_acceso', models.CharField(max_length=50, unique=True, verbose_name='Clave de Acceso')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.clientes')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'facturas',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('iva', models.DecimalField(decimal_places=2, default=0.12, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventas.articulos')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventas.factura')),
            ],
            options={
                'verbose_name': 'Detalle Factura',
                'verbose_name_plural': 'Detalles Factura',
                'db_table': 'detalles_factura',
            },
        ),
    ]
