# Generated by Django 5.1.5 on 2025-02-06 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_factura_detallefactura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='clave_acceso',
        ),
    ]
